### ISSUE TITLE
libipt_FULLCONENAT.c:6:10: fatal error: xtables.h: No such file or directory

### ISSUE THREAD

**Issue by 0x5e** [LGA1150/openwrt-fullconenat#6]
网上说是要装iptables-dev，已经安装了还是有这个问题。我是用github action + ubuntu + openwrt sdk编译的，请问还有什么要注意的吗？

```
aarch64-openwrt-linux-musl-gcc -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/runner/work/build-openwrt-package/build-openwrt-package/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/fullconenat-2018-12-15-d4daedd0:fullconenat-2018-12-15-d4daedd0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/runner/work/build-openwrt-package/build-openwrt-package/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/home/runner/work/build-openwrt-package/build-openwrt-package/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64/staging_dir/target-aarch64_cortex-a53_musl/include -I/home/runner/work/build-openwrt-package/build-openwrt-package/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/include -I/home/runner/work/build-openwrt-package/build-openwrt-package/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include/fortify -I/home/runner/work/build-openwrt-package/build-openwrt-package/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include  -fPIC -D_INIT=libipt_FULLCONENAT_init -c -o libipt_FULLCONENAT.o libipt_FULLCONENAT.c;
libipt_FULLCONENAT.c:6:10: fatal error: xtables.h: No such file or directory
 #include <xtables.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:4: recipe for target 'libipt_FULLCONENAT.o' failed
make[3]: *** [libipt_FULLCONENAT.o] Error 1
make[3]: Leaving directory '/home/runner/work/build-openwrt-package/build-openwrt-package/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/fullconenat-2018-12-15-d4daedd0'
```

```yml
name: Build Packages
on: push
env:
  SDK_URL: https://downloads.openwrt.org/releases/19.07.1/targets/sunxi/cortexa53/openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64.tar.xz
  FILE_NAME: openwrt-sdk-19.07.1-sunxi-cortexa53_gcc-7.5.0_musl.Linux-x86_64
  PACKAGE_URL: https://github.com/LGA1150/openwrt-fullconenat
  PACKAGE_NAME: iptables-mod-fullconenat 
  SSH_ACTIONS: false
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Install build tools
      run: |
        sudo apt-get install -y build-essential libncurses5-dev iptables-dev
    - name: Download SDK & Package
      run: |
        curl -fSL $SDK_URL | tar xJ
        cd $FILE_NAME
        git clone -b master --single-branch $PACKAGE_URL package/$PACKAGE_NAME
    - name: Make
      run: |
        cd $FILE_NAME
        echo "CONFIG_PACKAGE_iptables-mod-fullconenat=m" > .config
        make defconfig        
        make package/$PACKAGE_NAME/compile V=99
        ls bin/**/*.ipk
        # bin/packages/aarch64_cortex-a53/base/luci-app-openclash_0.32.3-0_all.ipk
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
```
